### PR TITLE
Add ng-packagr and bump prettier

### PR DESCRIPTION
**Pull request by Timebutt**
This PR adds `ng-packagr` ([link](https://github.com/ng-packagr/ng-packagr)), which builds a package that perfectly adheres to all Angular guidelines for a package. I added this, as I'm experiencing issues trying to build my project with the new Angular 8 `Ivy` compiler. When the package is built with `ng-packagr`, Ivy can happily build.

I also bumped `prettier` to the latest version and ran it on the code in repository.

### CODE REVIEW

**Comment by kzimny** [comment]
I tested the PR on my environment, no problem here. Thank you. @chymz could you merge and prepare next release please? Thank you.

**Comment by Timebutt** [comment]
Angular 8 was just released, would be nice if we could bump the version of this package so that people that use this package can start playing around with `Ivy`.

**Comment by kzimny** [comment]
@chymz please prepare npm package with the next version 1.2.3

**Comment by chymz** [comment]
`1.2.3` published, thanks @Timebutt & @kzimny

**Pull request merged**
