### PR TITLE
Added support for instanceReady event

### PR DESCRIPTION
**Pull request by danielcrisp**
Adds the ability to listen for the `instanceReady` event emitted by CKEditor. The event from CKEditor is sent to the `EventEmitter`, so as a bonus it means you can get a reference to the CKEditor instance itself by listening to the event in your parent component.

http://docs.ckeditor.com/#!/api/CKEDITOR-event-instanceReady

### CODE REVIEW

**Comment by danielcrisp** [comment]
I've changed `_onChangeCallback` to `onChange` so maybe this also fixes #20

**Comment by chymz** [comment]
Yeah ! Thanks for that dude !

**Comment by danielcrisp** [comment]
No worries, thanks for doing the hard bit!

**Comment by danielcrisp** [comment]
Would you mind adding a new version tag so I can get this with `npm` please?

**Comment by chymz** [comment]
v1.0.5 published

**Pull request merged**
