### PR TITLE
1.2.6

### PR DESCRIPTION
**Pull request by kzimny**
Remove languageLevel

### CODE REVIEW

**Comment by kzimny** [comment]
@chymz : may I ask you to create new npm package and publish the lib folder: ```npm publish lib```.
If you publish only with ```npm publish``` the compiled files are saved into libs and cannot be used. Thanks.

**Comment by chymz** [comment]
@kzimny 

Actually if I do a `npm publish lib` NPM understand that I want to publish a package named `lib`

If i do `npm publish ./lib` NPM shows an error that there is no `package.json` in this folder.

I think a build step is missing, I'll try to investigate...

**Comment by chymz** [comment]
@kzimny sorry, my mistake, everythin works as expected, 1.2.6 is now plublished

**Comment by kzimny** [comment]
Thanks! It works now.

**Pull request merged**
